/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         to: {
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             name: "Ada Lovelace",
 *             name2: "InGen Corporation"
 *         },
 *         from: {
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             name: "Hooli",
 *             name2: "InGen Corporation"
 *         }
 *     }
 */
export interface MailingRequestSchema {
    to: Abound.MailingRequestToSchema;
    from: Abound.MailingRequestFromSchema;
}
