/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * The mailing address of the sender.
 */
export interface MailingRequestFromSchema extends Abound.MailingNameSchema, Abound.types.AddressSchema {}
