/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * The mailing address of the recipient.
 */
export interface MailingRequestToSchema extends Abound.MailingNameSchema, Abound.types.AddressSchema {}
