/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../../index";

/**
 * The payee of the document.
 */
export interface PayeeSchema extends Abound.types.PayeeRequestSchema {
    tinFingerprint: Abound.types.TinFingerprint;
    tinType?: Abound.types.TinTypeEnum;
    tinVerificationId: Abound.types.TinVerificationId;
    tinVerificationStatus: Abound.types.TinVerificationStatusEnum;
}
