/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../index";

/**
 * @example
 *     {}
 */
export interface MailingsListRequest {
    page?: Abound.types.Page;
    /**
     * Filters the list of mailings based on the `status` field.
     */
    status?: Abound.MailingStatusEnum;
    userId?: Abound.types.UserId;
}
