/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../index";

/**
 * @example
 *     {
 *         body: {
 *             payee: {
 *                 name: "Ada Lovelace",
 *                 tin: "000000000",
 *                 address: "1401 N Shoreline Blvd",
 *                 address2: "Suite 1",
 *                 city: "Mountain View",
 *                 state: "CA",
 *                 postalCode: "94043",
 *                 country: "US"
 *             },
 *             formFields: {
 *                 nonemployeeCompensation: 10000,
 *                 accountNumber: "A0NEqtav7n0sBGoq88w0",
 *                 stateTaxInfo: [{
 *                         filingState: "CA",
 *                         stateIncome: 10000
 *                     }]
 *             }
 *         }
 *     }
 */
export interface Form1099NecCorrectRequest {
    "Idempotency-Key"?: Abound.types.IdempotencyKey | undefined;
    body: Abound.Form1099NecCorrectRequestSchema;
}
