/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         id: "documentId_sampletTtqNfulW8",
 *         formFields: {
 *             isCorrected: false,
 *             isVoid: false,
 *             accountNumber: "A0MCFOfvWWL7AVtwrhiU",
 *             aggregateGrossAmount: 27987876,
 *             aggregateGrossAmountCardNotPresent: 2332323,
 *             federalIncomeTaxWithheld: 0,
 *             merchantCategoryCode: "4582",
 *             numberOfPaymentTransactions: 767,
 *             pseName: "Payment Entity",
 *             payerClassification: Abound.Form1099KPayerClassificationEnum.Pse,
 *             transactionsReportedClassification: Abound.Form1099KTransactionsReportedClassificationSchema.PaymentCard,
 *             psePhoneNumber: "+15555555555",
 *             grossAmountsByMonth: {
 *                 april: 2332323,
 *                 august: 2332323,
 *                 december: 2332323,
 *                 february: 2332323,
 *                 january: 2332323,
 *                 july: 2332323,
 *                 june: 2332323,
 *                 march: 2332323,
 *                 may: 2332323,
 *                 november: 2332323,
 *                 october: 2332323,
 *                 september: 2332323
 *             },
 *             stateTaxInfo: [{
 *                     filingState: Abound.types.Form1099FilingStateEnum.Ca,
 *                     stateTaxWithheld: 0
 *                 }]
 *         },
 *         filingYear: 2024,
 *         createdAt: "2024-01-01T00:00:00.000Z",
 *         status: Abound.types.Form1099StatusEnum.Created,
 *         payer: {
 *             name: "Hooli",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             phoneNumber: "+16501014096",
 *             tin: "*******11",
 *             tinType: Abound.types.TinTypeEnum.Business,
 *             tinFingerprint: "tinFingerprint_sample847jI1LwxF",
 *             tinVerificationId: "tinVerificationId_sample1b0E6efa89",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payee: {
 *             name: "Ada Lovelace",
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             tin: "*******00",
 *             tinType: Abound.types.TinTypeEnum.Individual,
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payerUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-COPY-C.pdf",
 *         payeeUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-COPY-B.pdf"
 *     }
 *
 * @example
 *     {
 *         id: "documentId_sampletTtqNfulW8",
 *         formFields: {
 *             isCorrected: false,
 *             isVoid: false,
 *             accountNumber: "A0MCFOfvWWL7AVtwrhiU",
 *             aggregateGrossAmount: 27987876,
 *             aggregateGrossAmountCardNotPresent: 2332323,
 *             federalIncomeTaxWithheld: 0,
 *             merchantCategoryCode: "4582",
 *             numberOfPaymentTransactions: 767,
 *             pseName: "Payment Entity",
 *             payerClassification: Abound.Form1099KPayerClassificationEnum.Pse,
 *             transactionsReportedClassification: Abound.Form1099KTransactionsReportedClassificationSchema.PaymentCard,
 *             psePhoneNumber: "+15555555555",
 *             grossAmountsByMonth: {
 *                 april: 2332323,
 *                 august: 2332323,
 *                 december: 2332323,
 *                 february: 2332323,
 *                 january: 2332323,
 *                 july: 2332323,
 *                 june: 2332323,
 *                 march: 2332323,
 *                 may: 2332323,
 *                 november: 2332323,
 *                 october: 2332323,
 *                 september: 2332323
 *             },
 *             stateTaxInfo: [{
 *                     filingState: Abound.types.Form1099FilingStateEnum.Ca,
 *                     stateTaxWithheld: 0
 *                 }]
 *         },
 *         filingYear: 2024,
 *         createdAt: "2024-01-01T00:00:00.000Z",
 *         status: Abound.types.Form1099StatusEnum.Filed,
 *         payer: {
 *             name: "Hooli",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             phoneNumber: "+16501014096",
 *             tin: "*******11",
 *             tinType: Abound.types.TinTypeEnum.Business,
 *             tinFingerprint: "tinFingerprint_sample847jI1LwxF",
 *             tinVerificationId: "tinVerificationId_sample1b0E6efa89",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payee: {
 *             name: "Ada Lovelace",
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             tin: "*******00",
 *             tinType: Abound.types.TinTypeEnum.Individual,
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payerUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-COPY-C.pdf",
 *         payeeUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-COPY-B.pdf"
 *     }
 *
 * @example
 *     {
 *         id: "documentId_samplenOHhUUVnh6",
 *         correctedFromId: "documentId_sampletTtqNfulW8",
 *         formFields: {
 *             isCorrected: true,
 *             isVoid: false,
 *             accountNumber: "A0MCFOfvWWL7AVtwrhiU",
 *             aggregateGrossAmount: 25655553,
 *             aggregateGrossAmountCardNotPresent: 25655553,
 *             federalIncomeTaxWithheld: 0,
 *             merchantCategoryCode: "4582",
 *             numberOfPaymentTransactions: 767,
 *             pseName: "Payment Entity",
 *             payerClassification: Abound.Form1099KPayerClassificationEnum.Pse,
 *             transactionsReportedClassification: Abound.Form1099KTransactionsReportedClassificationSchema.PaymentCard,
 *             psePhoneNumber: "+15555555555",
 *             grossAmountsByMonth: {
 *                 april: 2332323,
 *                 august: 2332323,
 *                 december: 2332323,
 *                 february: 2332323,
 *                 january: 0,
 *                 july: 2332323,
 *                 june: 2332323,
 *                 march: 2332323,
 *                 may: 2332323,
 *                 november: 2332323,
 *                 october: 2332323,
 *                 september: 2332323
 *             },
 *             stateTaxInfo: [{
 *                     filingState: Abound.types.Form1099FilingStateEnum.Ca,
 *                     stateTaxWithheld: 0
 *                 }]
 *         },
 *         filingYear: 2024,
 *         createdAt: "2024-01-01T00:00:00.000Z",
 *         status: Abound.types.Form1099StatusEnum.Filed,
 *         payer: {
 *             name: "Hooli",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             phoneNumber: "+16501014096",
 *             tin: "*******11",
 *             tinType: Abound.types.TinTypeEnum.Business,
 *             tinFingerprint: "tinFingerprint_sample847jI1LwxF",
 *             tinVerificationId: "tinVerificationId_sample1b0E6efa89",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payee: {
 *             name: "Ada Lovelace",
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             tin: "*******00",
 *             tinType: Abound.types.TinTypeEnum.Individual,
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payerUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-CORRECTED-COPY-C.pdf",
 *         payeeUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-CORRECTED-COPY-B.pdf"
 *     }
 *
 * @example
 *     {
 *         id: "documentId_sampleb6HQLsVuM9",
 *         voidedFromId: "documentId_sampletTtqNfulW8",
 *         formFields: {
 *             isCorrected: false,
 *             isVoid: true,
 *             accountNumber: "A0MCFOfvWWL7AVtwrhiU",
 *             aggregateGrossAmount: 27987876,
 *             aggregateGrossAmountCardNotPresent: 2332323,
 *             federalIncomeTaxWithheld: 0,
 *             merchantCategoryCode: "4582",
 *             numberOfPaymentTransactions: 767,
 *             pseName: "Payment Entity",
 *             payerClassification: Abound.Form1099KPayerClassificationEnum.Pse,
 *             transactionsReportedClassification: Abound.Form1099KTransactionsReportedClassificationSchema.PaymentCard,
 *             psePhoneNumber: "+15555555555",
 *             grossAmountsByMonth: {
 *                 april: 2332323,
 *                 august: 2332323,
 *                 december: 2332323,
 *                 february: 2332323,
 *                 january: 2332323,
 *                 july: 2332323,
 *                 june: 2332323,
 *                 march: 2332323,
 *                 may: 2332323,
 *                 november: 2332323,
 *                 october: 2332323,
 *                 september: 2332323
 *             },
 *             stateTaxInfo: [{
 *                     filingState: Abound.types.Form1099FilingStateEnum.Ca,
 *                     stateTaxWithheld: 0
 *                 }]
 *         },
 *         filingYear: 2024,
 *         createdAt: "2024-01-01T00:00:00.000Z",
 *         status: Abound.types.Form1099StatusEnum.Filed,
 *         payer: {
 *             name: "Hooli",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             phoneNumber: "+16501014096",
 *             tin: "*******11",
 *             tinType: Abound.types.TinTypeEnum.Business,
 *             tinFingerprint: "tinFingerprint_sample847jI1LwxF",
 *             tinVerificationId: "tinVerificationId_sample1b0E6efa89",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payee: {
 *             name: "Ada Lovelace",
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             tin: "*******00",
 *             tinType: Abound.types.TinTypeEnum.Individual,
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payerUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-VOID-COPY-C.pdf",
 *         payeeUrl: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/FORM-1099-K-VOID-COPY-B.pdf"
 *     }
 */
export interface Form1099KSchema extends Abound.types.Form1099BaseSchema {
    formFields: Abound.Form1099KFormFieldsSchema;
}
