/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Abound from "../index";

export class ConflictError extends errors.AboundError {
    constructor(body: Abound.ErrorSchema) {
        super({
            message: "ConflictError",
            statusCode: 409,
            body: body,
        });
        Object.setPrototypeOf(this, ConflictError.prototype);
    }
}
