/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../index";

/**
 * @example
 *     {}
 */
export interface FormW9ListRequest {
    page?: Abound.types.Page;
    payeeTinFingerprint?: Abound.types.PayeeTinFingerprint;
    payerTinFingerprint?: Abound.types.PayerTinFingerprint;
    userId?: Abound.types.UserId;
}
