/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface FormW9ListRequest {
    /**
     * The specific page of results you're requesting. Responses are limited to a maximum of 100 records.
     */
    page?: number;
    /**
     * Filters the list of documents based on the `payee.tinFingerprint` field.
     */
    payeeTinFingerprint?: string;
    /**
     * Filters the list of documents based on the `payer.tinFingerprint` field.
     */
    payerTinFingerprint?: string;
    /**
     * The unique identifier for a single end-user of your application.
     */
    userId?: string;
}
