/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as AboundApi from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace TinVerifications {
    interface Options {
        environment?: core.Supplier<environments.AboundApiEnvironment | string>;
        token: core.Supplier<core.BearerToken>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}

export class TinVerifications {
    constructor(protected readonly _options: TinVerifications.Options) {}

    /**
     * Returns a list of TIN verifications. Up to 100 TIN verifications are returned per request.
     *
     * @param {AboundApi.TinVerificationsListRequest} request
     * @param {TinVerifications.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AboundApi.BadRequestError}
     * @throws {@link AboundApi.UnauthorizedError}
     * @throws {@link AboundApi.NotFoundError}
     * @throws {@link AboundApi.InternalServerError}
     *
     * @example
     *     await client.tinVerifications.list()
     */
    public async list(
        request: AboundApi.TinVerificationsListRequest = {},
        requestOptions?: TinVerifications.RequestOptions
    ): Promise<AboundApi.TinVerificationSchema[]> {
        const { page, tinFingerprint, status, userId } = request;
        const _queryParams: Record<string, string | string[] | object | object[]> = {};
        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (tinFingerprint != null) {
            _queryParams["tinFingerprint"] = tinFingerprint;
        }

        if (status != null) {
            _queryParams["status"] = status;
        }

        if (userId != null) {
            _queryParams["userId"] = userId;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.AboundApiEnvironment.Production,
                "tin-verifications"
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "abound",
                "X-Fern-SDK-Version": "0.0.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as AboundApi.TinVerificationSchema[];
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AboundApi.BadRequestError(_response.error.body as AboundApi.ErrorBadRequestSchema);
                case 401:
                    throw new AboundApi.UnauthorizedError(_response.error.body as AboundApi.ErrorSchema);
                case 404:
                    throw new AboundApi.NotFoundError(_response.error.body as AboundApi.ErrorSchema);
                case 500:
                    throw new AboundApi.InternalServerError(_response.error.body as AboundApi.ErrorSchema);
                default:
                    throw new errors.AboundApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AboundApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AboundApiTimeoutError();
            case "unknown":
                throw new errors.AboundApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Creates an asynchronous TIN verification.
     *
     * @param {AboundApi.TinVerificationsCreateRequest} request
     * @param {TinVerifications.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AboundApi.BadRequestError}
     * @throws {@link AboundApi.UnauthorizedError}
     * @throws {@link AboundApi.NotFoundError}
     * @throws {@link AboundApi.InternalServerError}
     *
     * @example
     *     await client.tinVerifications.create({
     *         "Idempotency-Key": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
     *         body: {
     *             name: "Ada Lovelace",
     *             tin: "000000000"
     *         }
     *     })
     */
    public async create(
        request: AboundApi.TinVerificationsCreateRequest,
        requestOptions?: TinVerifications.RequestOptions
    ): Promise<AboundApi.TinVerificationSchema> {
        const { "Idempotency-Key": idempotencyKey, body: _body } = request;
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.AboundApiEnvironment.Production,
                "tin-verifications"
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "abound",
                "X-Fern-SDK-Version": "0.0.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                "Idempotency-Key": idempotencyKey != null ? idempotencyKey : undefined,
            },
            contentType: "application/json",
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as AboundApi.TinVerificationSchema;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AboundApi.BadRequestError(_response.error.body as AboundApi.ErrorBadRequestSchema);
                case 401:
                    throw new AboundApi.UnauthorizedError(_response.error.body as AboundApi.ErrorSchema);
                case 404:
                    throw new AboundApi.NotFoundError(_response.error.body as AboundApi.ErrorSchema);
                case 500:
                    throw new AboundApi.InternalServerError(_response.error.body as AboundApi.ErrorSchema);
                default:
                    throw new errors.AboundApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AboundApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AboundApiTimeoutError();
            case "unknown":
                throw new errors.AboundApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieves the details of an existing TIN verification.
     *
     * @param {string} tinVerificationId - The unique identifier for an existing TIN verification.
     * @param {TinVerifications.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AboundApi.BadRequestError}
     * @throws {@link AboundApi.UnauthorizedError}
     * @throws {@link AboundApi.NotFoundError}
     * @throws {@link AboundApi.InternalServerError}
     *
     * @example
     *     await client.tinVerifications.retrieve("{{tinVerificationId}}")
     */
    public async retrieve(
        tinVerificationId: string,
        requestOptions?: TinVerifications.RequestOptions
    ): Promise<AboundApi.TinVerificationSchema> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.AboundApiEnvironment.Production,
                `tin-verifications/${encodeURIComponent(tinVerificationId)}`
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "abound",
                "X-Fern-SDK-Version": "0.0.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as AboundApi.TinVerificationSchema;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AboundApi.BadRequestError(_response.error.body as AboundApi.ErrorBadRequestSchema);
                case 401:
                    throw new AboundApi.UnauthorizedError(_response.error.body as AboundApi.ErrorSchema);
                case 404:
                    throw new AboundApi.NotFoundError(_response.error.body as AboundApi.ErrorSchema);
                case 500:
                    throw new AboundApi.InternalServerError(_response.error.body as AboundApi.ErrorSchema);
                default:
                    throw new errors.AboundApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AboundApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AboundApiTimeoutError();
            case "unknown":
                throw new errors.AboundApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
