/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         id: "documentId_sampleGNPOKNmIgF",
 *         userId: "userId_sampleXGMFnhOpeR",
 *         formFields: {},
 *         filingYear: 2023,
 *         createdAt: new Date("2024-01-01T00:00:00.000Z"),
 *         status: Abound.types.Form1099StatusEnum.Created,
 *         payer: {
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             name: "Hooli",
 *             name2: "Hooli",
 *             phoneNumber: "6501014096",
 *             tin: "*******11",
 *             tinFingerprint: "tinFingerprint_sample847jI1LwxF",
 *             tinVerificationId: "tinVerificationId_sample1b0E6efa89",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payee: {
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             name: "Ada Lovelace",
 *             name2: "InGen Corporation",
 *             tin: "*******00",
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payerUrl: "https://documents.withabound.com/documentId_sampleGNPOKNmIgF",
 *         payeeUrl: "https://documents.withabound.com/documentId_sampleGNPOKNmIgF"
 *     }
 *
 * @example
 *     {
 *         id: "documentId_sampleGNPOKNmIgF",
 *         userId: "userId_sampleXGMFnhOpeR",
 *         formFields: {},
 *         filingYear: 2023,
 *         createdAt: new Date("2024-01-01T00:00:00.000Z"),
 *         status: Abound.types.Form1099StatusEnum.Filed,
 *         payer: {
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             name: "Hooli",
 *             name2: "Hooli",
 *             phoneNumber: "6501014096",
 *             tin: "*******11",
 *             tinFingerprint: "tinFingerprint_sample847jI1LwxF",
 *             tinVerificationId: "tinVerificationId_sample1b0E6efa89",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payee: {
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             name: "Ada Lovelace",
 *             name2: "InGen Corporation",
 *             tin: "*******00",
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         payerUrl: "https://documents.withabound.com/documentId_sampleGNPOKNmIgF",
 *         payeeUrl: "https://documents.withabound.com/documentId_sampleGNPOKNmIgF"
 *     }
 */
export interface Form1099MiscSchema extends Abound.types.Form1099BaseSchema {
    formFields: Abound.Form1099MiscFormFieldsSchema;
}
