/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         filingYear: 2023,
 *         payer: {
 *             name: "Hooli",
 *             tin: "111111111",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             phoneNumber: "+16501014096"
 *         },
 *         payee: {
 *             name: "Ada Lovelace",
 *             tin: "000000000",
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US"
 *         },
 *         formFields: {
 *             cropInsuranceProceeds: 97109,
 *             excessGoldenParachutePayments: 97109,
 *             federalIncomeTaxWithheld: 0,
 *             fishPurchasedForResale: 97109,
 *             fishingBoatProceeds: 97109,
 *             grossProceedsPaidToAnAttorney: 97109,
 *             hasDirectSalesOver5000: false,
 *             hasFatcaFilingRequirement: true,
 *             medicalAndHealthCarePayments: 97109,
 *             nonqualifiedDeferredCompensation: 97109,
 *             substitutePaymentsInLieuOfDividendsOrInterest: 97109,
 *             otherIncome: 97109,
 *             rents: 97109,
 *             royalties: 97109,
 *             section409ADeferrals: 97109,
 *             accountNumber: "A00AskD1ZTO4YB8oBHav",
 *             stateTaxInfo: [{
 *                     filingState: Abound.types.Form1099FilingStateEnum.Ca,
 *                     stateIncome: 345543,
 *                     stateTaxWithheld: 0
 *                 }]
 *         }
 *     }
 */
export interface Form1099MiscRequestSchema extends Abound.types.Form1099BaseRequestSchema {
    formFields: Abound.Form1099MiscFormFieldsRequestSchema;
}
