/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * The component customizations for this access token.
 */
export interface CustomizationsSchema {
    /** The Payee Tax Profile component customizations. */
    payeeTaxProfile?: Abound.PayeeTaxProfileSchema;
}
