/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

export interface PayeeTaxProfileSchema {
    /** Determines if Abound should preload the Payee Tax Profile by `userId` lookup. Default is `true`. */
    shouldPreloadFromUserId?: boolean;
    /** Determines if the electronic delivery consent question should be asked in the Payee Tax Profile component. Default is `true`. */
    shouldCollectElectronicDeliveryConsent?: boolean;
    /** A list of the forms your organizaton intends to support and collect during a Payee Tax Profile submission. Default is all forms: `["FORM_W_9", "FORM_W_8BEN", "FORM_W_8BEN_E"]`. */
    supportedTaxForms?: Abound.SupportedTaxFormsEnum[];
    /** Used to preload the Payee Tax Profile with default values. These defaults will be ignored if data is preloaded by `userId`. */
    defaults?: Abound.DefaultsSchema;
    /** If supplied, a Payee Tax Profile submission that creates a Form W-9 will attach this information as the `Payer`. */
    requestingPayer?: Abound.types.PayerRequestSchema;
}
