/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

export interface W8BenFormFieldsSchema {
    /** The tax classification of the payee. */
    taxClassification: "INDIVIDUAL";
    /** Pass true if a foreign TIN is not legally required. Otherwise false. */
    isForeignTinNotRequired?: boolean;
    /** The tax treaty benefits the payee is claiming. */
    taxTreatyBenefits?: Abound.types.TaxTreatyBenefitsSchema;
    /** The reference numbers to list on this W-8BEN. Two reference numbers are allowed. Max 20 characters each. */
    referenceNumbers?: string[];
    /** Pass true if the payee has certified the W-8BEN. Otherwise false. */
    isCertified: boolean;
    /** The electronic signature of the payee. */
    electronicSignature?: Abound.types.ElectronicSignatureOfPayeeSchema;
}
