/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WebhookPayloadBaseSchema {
    /** The id of the webhook attempt */
    id: string;
    /** The id of the webhook event */
    webhookId: string;
    /** The date and time in `ISO 8601` format when the webhook attempt was triggered */
    timestamp: string;
    /** The id of the resource that triggered the webhook */
    resourceId: string;
    /** The URL of the resource that triggered the webhook */
    resourceUrl: string;
}
