/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DefaultErrorSchema {
    /** The error message associated with the response status code. */
    message: string;
}
