/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface ElectronicSignatureSchema {
    electronicSignature?: AboundApi.ElectronicSignatureNestedOptionalSchema;
}
