/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface Form1099IntFormFieldsSchema {
    formFields?: Abound.OneThousandNinetyNineIntFormFieldsSchemaFormFields;
}
