/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface Form1099NecSchema
    extends Abound.Form1099Schema,
        Abound.Form1099RequestSchema,
        Abound.ReferencesSchema,
        Abound.Form1099RelationsSchema {
    /** The unique identifier for this 1099-NEC document. */
    id: string;
    payer?: Abound.PayerNestedOptionalSchema;
    payee?: Abound.PayeeNestedOptionalSchema;
    formFields?: Abound.OneThousandNinetyNineCorrectionFormFieldsSchemaFormFields;
}
