/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MailingNameSchema {
    /** The individual's name (first + last) or business name. */
    name?: string;
    /** The business name, trade name, DBA name, or disregarded entity name, if different from `name`. */
    name2?: string;
}
