/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface MailingRequestSchema {
    /** The mailing address of the recipient. */
    to: AboundApi.MailingRequestSchemaTo;
    /** The mailing address of the sender. */
    from: AboundApi.MailingRequestSchemaFrom;
}
