/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface OneThousandNinetyNineNecFormFieldsSchemaFormFields
    extends Abound.Form1099NecNestedFormFieldsOptionalSchema,
        Abound.StateTaxInfoWithIncomeSchema {}
