/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface OneThousandNinetyNineKFormFieldsSchemaFormFields
    extends Abound.Form1099KNestedFormFieldsOptionalSchema,
        Abound.StateTaxInfoSchema {}
