/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of payer. Payment settlement entity (PSE) or Electronic Payment Facilitator (EPF)/Other third party.
 */
export type OneThousandNinetyNineKNestedFormFieldsOptionalSchemaPayerClassification = "PSE" | "EPF_OTHER";

export const OneThousandNinetyNineKNestedFormFieldsOptionalSchemaPayerClassification = {
    Pse: "PSE",
    EpfOther: "EPF_OTHER",
} as const;
