/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An object that contains the gross amount of transactions for each month. At least one month must have a value above zero. Values must be in cents.
 */
export interface OneThousandNinetyNineKNestedFormFieldsOptionalSchemaGrossAmountsByMonth {
    /** The gross amount of payment card/third party network transactions made to you in January. Value must be in cents. */
    january?: number;
    /** The gross amount of payment card/third party network transactions made to you in February. Value must be in cents. */
    february?: number;
    /** The gross amount of payment card/third party network transactions made to you in March. Value must be in cents. */
    march?: number;
    /** The gross amount of payment card/third party network transactions made to you in April. Value must be in cents. */
    april?: number;
    /** The gross amount of payment card/third party network transactions made to you in May. Value must be in cents. */
    may?: number;
    /** The gross amount of payment card/third party network transactions made to you in June. Value must be in cents. */
    june?: number;
    /** The gross amount of payment card/third party network transactions made to you in July. Value must be in cents. */
    july?: number;
    /** The gross amount of payment card/third party network transactions made to you in August. Value must be in cents. */
    august?: number;
    /** The gross amount of payment card/third party network transactions made to you in September. Value must be in cents. */
    september?: number;
    /** The gross amount of payment card/third party network transactions made to you in October. Value must be in cents. */
    october?: number;
    /** The gross amount of payment card/third party network transactions made to you in November. Value must be in cents. */
    november?: number;
    /** The gross amount of payment card/third party network transactions made to you in December. Value must be in cents. */
    december?: number;
}
