/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface OneThousandNinetyNineKFormFieldsSchemaFormFields
    extends AboundApi.OneThousandNinetyNineKNestedFormFieldsOptionalSchema,
        AboundApi.StateTaxInfoSchema {}
