/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the payer's associated tin verification.
 */
export type PayerTinSchemaPayerTinVerificationStatus = "PENDING" | "MATCH" | "MISMATCH";

export const PayerTinSchemaPayerTinVerificationStatus = {
    Pending: "PENDING",
    Match: "MATCH",
    Mismatch: "MISMATCH",
} as const;
