/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PayeeForeignTinOptionalSchemaPayee {
    /** The fingerprint of the payee's Foreign TIN (FTIN). */
    foreignTinFingerprint?: string;
}
