/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the payee's associated tin verification.
 */
export type PayeeTinOptionalSchemaPayeeTinVerificationStatus = "PENDING" | "MATCH" | "MISMATCH";

export const PayeeTinOptionalSchemaPayeeTinVerificationStatus = {
    Pending: "PENDING",
    Match: "MATCH",
    Mismatch: "MISMATCH",
} as const;
