/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface PayeeTinOptionalSchemaPayee {
    /** The type of the payee's TIN. */
    tinType?: AboundApi.PayeeTinOptionalSchemaPayeeTinType;
    /** The fingerprint of the payee's TIN. */
    tinFingerprint?: string;
    /** The unique identifier of the payee's associated tin verification. */
    tinVerificationId?: string;
    /** The status of the payee's associated tin verification. */
    tinVerificationStatus?: AboundApi.PayeeTinOptionalSchemaPayeeTinVerificationStatus;
}
