/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface PayerTinSchemaPayer {
    /** The type of the payer's TIN. */
    tinType?: Abound.PayerTinSchemaPayerTinType;
    /** The fingerprint of the payer's TIN. */
    tinFingerprint: string;
    /** The unique identifier of the payer's associated tin verification. */
    tinVerificationId: string;
    /** The status of the payer's associated tin verification. */
    tinVerificationStatus: Abound.PayerTinSchemaPayerTinVerificationStatus;
}
