/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface PayeeNestedOptionalSchema extends AboundApi.AddressOptionalSchema {
    /** The payee's legal name (first + last) or business name. */
    name?: string;
    /** The payee's trade name, DBA name, or disregarded entity name, if different from `name`. */
    name2?: string;
    /** The payee's tax identification number, commonly referred to as a TIN. No hyphens. Numerical digits only. Alternatively, you may pass the corresponding `tinFingerprint`. */
    tin?: string;
}
