/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface StateTaxInfoNestedOptionalSchema {
    /** The filing state code. The abbreviation of the state (`CA` for California). */
    filingState?: Abound.StateTaxInfoNestedOptionalSchemaFilingState;
    /** The payee's state identification number. */
    payeeStateId?: string;
    /** The payer's state identification number. */
    payerStateId?: string;
    /** The state tax withheld. Value must be in cents. Abound does not currently support `stateTaxWithheld` reporting, please contact us for more information. */
    stateTaxWithheld?: number;
}
