/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface StateTaxInfoSchema {
    /** An array that contains up to two (1) state tax information objects. */
    stateTaxInfo?: Abound.StateTaxInfoNestedOptionalSchema[];
}
