/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface StateTaxInfoWithIncomeSchema {
    /** An array that contains up to two (1) state tax information objects. */
    stateTaxInfo?: AboundApi.StateTaxInfoWithIncomeNestedOptionalSchema[];
}
