/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface TinVerificationSchema extends Abound.TinVerificationRequestSchema {
    /** The unique identifier for this TIN verification. */
    id: string;
    /** The creation date and time of the TIN verification in `ISO 8601` format. */
    createdAt: string;
    /** The status of the TIN verification. */
    status: Abound.TinVerificationSchemaStatus;
    /** The type of TIN. */
    tinType?: Abound.TinVerificationSchemaTinType;
    /** The fingerprint for this TIN verification. */
    tinFingerprint: string;
}
