/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of TIN.
 */
export type TinVerificationSchemaTinType = "INDIVIDUAL" | "BUSINESS";

export const TinVerificationSchemaTinType = {
    Individual: "INDIVIDUAL",
    Business: "BUSINESS",
} as const;
