/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface TinVerificationSchema extends AboundApi.TinVerificationRequestSchema {
    /** The unique identifier for this TIN verification. */
    id: string;
    /** The creation date and time of the TIN verification in `ISO 8601` format. */
    createdAt: string;
    /** The status of the TIN verification. */
    status: AboundApi.TinVerificationSchemaStatus;
    /** The type of TIN. */
    tinType?: AboundApi.TinVerificationSchemaTinType;
    /** The fingerprint for this TIN verification. */
    tinFingerprint: string;
}
