/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the TIN verification.
 */
export type TinVerificationSchemaStatus = "PENDING" | "MATCH" | "MISMATCH";

export const TinVerificationSchemaStatus = {
    Pending: "PENDING",
    Match: "MATCH",
    Mismatch: "MISMATCH",
} as const;
