/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface UserSchema extends AboundApi.UserRequestSchema {
    /** The unique identifier for this user. */
    id: string;
    /** The creation date and time of the user in `ISO 8601` format. */
    createdAt: string;
}
