/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

export interface W8BenBeneficialOwnerSchema {
    payee?: Abound.W8BenBeneficialOwnerNestedOptionalSchema;
}
