/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface W8BenBeneficialOwnerSchema {
    payee?: AboundApi.W8BenBeneficialOwnerNestedOptionalSchema;
}
