/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The tax classification of the payee.
 */
export type W8BenESchemaFormFieldsTaxClassification =
    | "CENTRAL_BANK_OF_ISSUE"
    | "COMPLEX_TRUST"
    | "CORPORATION"
    | "DISREGARDED_ENTITY"
    | "ESTATE"
    | "FOREIGN_GOVERNMENT_CONTROLLED_ENTITY"
    | "FOREIGN_GOVERNMENT_INTEGRAL_PART"
    | "GRANTOR_TRUST"
    | "INTERNATIONAL_ORGANIZATION"
    | "PARTNERSHIP"
    | "PRIVATE_FOUNDATION"
    | "SIMPLE_TRUST"
    | "TAX_EXEMPT_ORGANIZATION";

export const W8BenESchemaFormFieldsTaxClassification = {
    CentralBankOfIssue: "CENTRAL_BANK_OF_ISSUE",
    ComplexTrust: "COMPLEX_TRUST",
    Corporation: "CORPORATION",
    DisregardedEntity: "DISREGARDED_ENTITY",
    Estate: "ESTATE",
    ForeignGovernmentControlledEntity: "FOREIGN_GOVERNMENT_CONTROLLED_ENTITY",
    ForeignGovernmentIntegralPart: "FOREIGN_GOVERNMENT_INTEGRAL_PART",
    GrantorTrust: "GRANTOR_TRUST",
    InternationalOrganization: "INTERNATIONAL_ORGANIZATION",
    Partnership: "PARTNERSHIP",
    PrivateFoundation: "PRIVATE_FOUNDATION",
    SimpleTrust: "SIMPLE_TRUST",
    TaxExemptOrganization: "TAX_EXEMPT_ORGANIZATION",
} as const;
