/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../index";

/**
 * The payee (benefical owner) completing the document.
 */
export interface W8BenEBeneficialOwnerNestedOptionalSchema {
    /** The payee's legal business name. */
    name?: string;
    /** The payee's trade name, DBA name, or disregarded entity name, if different from `name`. */
    name2?: string;
    /** The payee's country of incorporation adhering to `ISO 3166-2` standards. */
    incorporationCountry?: string;
    /** The payee's US tax identification number, commonly referred to as a TIN. No hyphens. Numerical digits only. Alternatively, you may pass the corresponding `tinFingerprint`. */
    tin?: string;
    /** The payee's foreign tax identifying number, commonly referred to as a FTIN. No hyphens. AlphaNumberic digits only. Alternatively, you may pass the corresponding `foreignTinFingerprint`. */
    foreignTin?: string;
    /** Permanent residence address (street, apt. or suite no., or rural route). Do not use a P.O. box or in-care-of address. */
    permanentResidenceAddress?: Abound.ForeignAddressOptionalSchema;
    /** The mailing address. Only include if different from the permanent residence address. */
    mailingAddress?: Abound.AddressOptionalSchema;
}
