/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../index";

export interface W9FormFieldsSchemaFormFields extends AboundApi.ElectronicSignatureSchema {
    /** The U.S. federal tax classification of the person. */
    taxClassification: AboundApi.W9FormFieldsSchemaFormFieldsTaxClassification;
    /** The tax classification of the payee if `taxClassification` is `OTHER`. */
    otherTaxClassification?: string;
    /** If your `taxClassification` is `PARTNERSHIP`, `TRUST`, `ESTATE`, or `LLC_PARTNERSHIP`, and you are providing this form to a partnership, trust, or estate in which you have an ownership interest, pass `true` if you have any foreign partners, owners, or beneficiaries. */
    hasIndirectForeignOwnership?: boolean;
    /** The code to identify a payee that is exempt from backup withholding. */
    exemptPayeeCode?: AboundApi.W9FormFieldsSchemaFormFieldsExemptPayeeCode;
    /** The code to identify a payee that is exempt from reporting under FATCA. */
    exemptFatcaCode?: AboundApi.W9FormFieldsSchemaFormFieldsExemptFatcaCode;
    /** The account numbers to list on this W-9. */
    accountNumbers?: string[];
    /** If the payee is subject to backup withholding, pass `true`. */
    isSubjectToBackupWithholding?: boolean;
    /** The certification date and time in `ISO 8601` format. This field is deprecated. Please use `electronicSignature` instead. */
    certifiedAt?: string;
}
