/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

export interface Form1099IntFormFieldsSchema
    extends Abound.types.Form1099FormFieldsBaseSchema,
        Abound.Form1099IntFormFieldsRequestSchema {}
