/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         filingYear: 2023,
 *         payer: {
 *             address: "1401 N Shoreline Blvd",
 *             address2: "Suite 1",
 *             city: "Mountain View",
 *             state: "CA",
 *             postalCode: "94043",
 *             country: "US",
 *             name: "Hooli",
 *             name2: "Hooli",
 *             tin: "111111111",
 *             phoneNumber: "6501014096"
 *         },
 *         payee: {
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             state: "CA",
 *             postalCode: "94306",
 *             country: "US",
 *             name: "Ada Lovelace",
 *             name2: "InGen Corporation",
 *             tin: "000000000"
 *         },
 *         formFields: {
 *             hasFatcaFilingRequirement: false,
 *             payersRoutingNumber: "123456789",
 *             interestIncome: 100000,
 *             stateTaxInfo: [{
 *                     filingState: Abound.types.Form1099FilingStateEnum.Ca,
 *                     stateTaxWithheld: 0
 *                 }]
 *         }
 *     }
 */
export interface Form1099IntRequestSchema extends Abound.types.Form1099BaseRequestSchema {
    formFields: Abound.Form1099IntFormFieldsRequestSchema;
}
