/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../index";

/**
 * @example
 *     {}
 */
export interface Form1099IntVoidRequest {
    "Idempotency-Key"?: Abound.types.IdempotencyKey | undefined;
}
