/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TinVerificationsListRequestStatus = "PENDING" | "MATCH" | "MISMATCH";

export const TinVerificationsListRequestStatus = {
    Pending: "PENDING",
    Match: "MATCH",
    Mismatch: "MISMATCH",
} as const;
