/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The customer-specific unique identifier associated to an Abound record. Allows developers to forego making their own tables every time they integrate and/or add an application.
 */
export type ForeignId = string;
