/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The specific page of results you're requesting. Responses are limited to a maximum of 100 records.
 */
export type Page = number;
