/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Filters the list of tax treaties based on the specified foreign `country`, adhering to `ISO 3166-2` standards.
 */
export type TaxTreatyCountry = string;
