/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The code to identify a payee that is exempt from backup withholding.
 */
export type W9ExemptPayeeCodeSchema = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13";

export const W9ExemptPayeeCodeSchema = {
    One: "1",
    Two: "2",
    Three: "3",
    Four: "4",
    Five: "5",
    Six: "6",
    Seven: "7",
    Eight: "8",
    Nine: "9",
    Ten: "10",
    Eleven: "11",
    Twelve: "12",
    Thirteen: "13",
} as const;
