/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The code to identify a payee that is exempt from reporting under FATCA.
 */
export type W9ExemptFatcaCodeSchema =
    | "A"
    | "B"
    | "C"
    | "D"
    | "E"
    | "F"
    | "G"
    | "H"
    | "I"
    | "J"
    | "K"
    | "L"
    | "M"
    | "NOT_APPLICABLE";

export const W9ExemptFatcaCodeSchema = {
    A: "A",
    B: "B",
    C: "C",
    D: "D",
    E: "E",
    F: "F",
    G: "G",
    H: "H",
    I: "I",
    J: "J",
    K: "K",
    L: "L",
    M: "M",
    NotApplicable: "NOT_APPLICABLE",
} as const;
