/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         payee: {
 *             name: "Ada Lovelace",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             country: "US",
 *             postalCode: "94306",
 *             state: "CA",
 *             tin: "000000000",
 *             tinType: Abound.types.TinTypeEnum.Individual
 *         },
 *         formFields: {
 *             taxClassification: Abound.W9TaxClassificationSchema.Individual,
 *             isSubjectToBackupWithholding: false,
 *             electronicSignature: {
 *                 signature: "Ada Lovelace",
 *                 printedName: "Ada Lovelace",
 *                 signedAt: new Date("2024-01-01T00:00:00.000Z"),
 *                 ipAddress: "127.0.0.1"
 *             }
 *         }
 *     }
 */
export interface W9RequestSchema {
    payee: Abound.types.PayeeWithOptionalTinTypeRequestSchema;
    payer?: Abound.types.PayerRequestSchema;
    formFields: Abound.W9FormFieldsSchema;
    userId?: Abound.types.UserId;
}
