/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../index";

/**
 * @example
 *     {
 *         id: "documentId_sampleVppNzzIbQT",
 *         createdAt: new Date("2024-01-01T00:00:00.000Z"),
 *         url: "https://documents.withabound.com/documentId_sampleVppNzzIbQT",
 *         payee: {
 *             name: "Ada Lovelace",
 *             address: "256 Byron Street",
 *             address2: "Suite 32",
 *             city: "Palo Alto",
 *             country: "US",
 *             postalCode: "94306",
 *             state: "CA",
 *             tin: "*******00",
 *             tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
 *             tinVerificationId: "tinVerificationId_sample41SD71AV8f",
 *             tinVerificationStatus: Abound.types.TinVerificationStatusEnum.Match
 *         },
 *         formFields: {
 *             taxClassification: Abound.W9TaxClassificationSchema.Individual,
 *             isSubjectToBackupWithholding: false,
 *             electronicSignature: {
 *                 signature: "Ada Lovelace",
 *                 printedName: "Ada Lovelace",
 *                 signedAt: new Date("2024-01-01T00:00:00.000Z"),
 *                 ipAddress: "127.0.0.1"
 *             }
 *         }
 *     }
 */
export interface W9Schema {
    /** The unique identifier for the W-9 document. */
    id: string;
    /** The date and time in `ISO 8601` format when the W-9 document was created. */
    createdAt: string;
    /** The URL to the W-9 document. */
    url: string;
    payee: Abound.types.PayeeSchema;
    payer?: Abound.types.PayerSchema;
    formFields: Abound.W9FormFieldsSchema;
    userId?: Abound.types.UserId;
}
