/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unique key used to identify a request that has already been processed.
 */
export type IdempotencyKey = string | undefined;
