/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AboundApi from "../../../../index";

/**
 * @example
 *     {
 *         "Idempotency-Key": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
 *         body: {
 *             id: "documentId_sampleGyuBXlfAwo",
 *             createdAt: new Date("2024-01-01T00:00:00.000Z"),
 *             expiresAt: new Date("2028-01-01T00:00:00.000Z"),
 *             url: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/documents/FORM-W-8BEN-E.pdf",
 *             formFields: {}
 *         }
 *     }
 */
export interface CreateW8BenERequest {
    /**
     * The unique key used to identify a request that has already been processed.
     */
    "Idempotency-Key"?: string;
    body: AboundApi.W8BenESchema;
}
