/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    sampleKey: process.env.appId_sampleqNhVcdYQYU.appSecret_sampleMz2Zbj3Hq || "test",
});

describe("ElectronicDeliveryConsent", () => {
    test("list", async () => {
        const response = await client.electronicDeliveryConsent.list();
        expect(response).toEqual([
            {
                id: "eDeliveryConsentId_sample7zmM4xCWxe",
                createdAt: new Date("2024-01-01T00:00:00.000Z"),
                status: "ASSENTED",
                email: "user1@example.com",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
            },
        ]);
    });
});
