/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    apiKey: process.env.TESTS_AUTH || "test",
});

describe("ElectronicDeliveryConsents", () => {
    test("list", async () => {
        const response = await client.electronicDeliveryConsents.list();
        expect(response).toEqual([
            {
                id: "eDeliveryConsentId_sample7zmM4xCWxe",
                createdAt: "2024-01-01T00:00:00.000Z",
                status: "ASSENTED",
                email: "your-users-email@domain.com",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
            },
        ]);
    });
});
