/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../src/api/index";
import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    sampleKey: process.env.appId_sampleqNhVcdYQYU.appSecret_sampleMz2Zbj3Hq || "test",
});

describe("Form1099Int", () => {
    test("list", async () => {
        const response = await client.form1099Int.list();
        expect(response).toEqual([
            {
                id: "documentId_samplepWpJ9Snlzb",
                userId: "userId_sampleXGMFnhOpeR",
                formFields: {},
                filingYear: 2023,
                createdAt: new Date("2024-01-01T00:00:00.000Z"),
                status: "FILED",
                payer: {
                    address: "1401 N Shoreline Blvd",
                    address2: "Suite 1",
                    city: "Mountain View",
                    state: "CA",
                    postalCode: "94043",
                    country: "US",
                    name: "Hooli",
                    name2: "Hooli",
                    phoneNumber: "6501014096",
                    tin: "*******11",
                    tinFingerprint: "tinFingerprint_sample847jI1LwxF",
                    tinVerificationId: "tinVerificationId_sample1b0E6efa89",
                    tinVerificationStatus: "MATCH",
                },
                payee: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    state: "CA",
                    postalCode: "94306",
                    country: "US",
                    name: "Ada Lovelace",
                    name2: "InGen Corporation",
                    tin: "*******00",
                    tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                    tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                    tinVerificationStatus: "MATCH",
                },
                payerUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
                payeeUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
            },
        ]);
    });

    test("create", async () => {
        const response = await client.form1099Int.create({
            body: {
                filingYear: 2023,
                payer: {
                    address: "1401 N Shoreline Blvd",
                    address2: "Suite 1",
                    city: "Mountain View",
                    state: "CA",
                    postalCode: "94043",
                    country: "US",
                    name: "Hooli",
                    name2: "Hooli",
                    tin: "111111111",
                    phoneNumber: "6501014096",
                },
                payee: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    state: "CA",
                    postalCode: "94306",
                    country: "US",
                    name: "Ada Lovelace",
                    name2: "InGen Corporation",
                    tin: "000000000",
                },
                formFields: {
                    hasFatcaFilingRequirement: false,
                    accountNumber: "123456789",
                    payersRoutingNumber: "123456789",
                    interestIncome: 100000,
                    stateTaxInfo: [
                        {
                            filingState: Abound.types.Form1099FilingStateEnum.Ca,
                            stateTaxWithheld: 0,
                        },
                    ],
                },
            },
        });
        expect(response).toEqual({
            id: "documentId_samplepWpJ9Snlzb",
            userId: "userId_sampleXGMFnhOpeR",
            formFields: {},
            filingYear: 2023,
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "CREATED",
            payer: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "Hooli",
                phoneNumber: "6501014096",
                tin: "*******11",
                tinFingerprint: "tinFingerprint_sample847jI1LwxF",
                tinVerificationId: "tinVerificationId_sample1b0E6efa89",
                tinVerificationStatus: "MATCH",
            },
            payee: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
                tin: "*******00",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            payerUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
            payeeUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
        });
    });

    test("mail", async () => {
        const response = await client.form1099Int.mail("documentId_samplepWpJ9Snlzb", {
            body: {
                to: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    state: "CA",
                    postalCode: "94306",
                    country: "US",
                    name: "Ada Lovelace",
                    name2: "InGen Corporation",
                },
                from: {
                    address: "1401 N Shoreline Blvd",
                    address2: "Suite 1",
                    city: "Mountain View",
                    state: "CA",
                    postalCode: "94043",
                    country: "US",
                    name: "Hooli",
                    name2: "InGen Corporation",
                },
            },
        });
        expect(response).toEqual({
            to: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
            },
            from: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "InGen Corporation",
            },
            id: "mailingId_sampleFV9b73IvAD",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "CREATED",
            url: "https://document.,withabound.com/documentId_samplepWpJ9Snlzb",
            userId: "userId_sampleXGMFnhOpeR",
            mailedFromId: "documentId_samplepWpJ9Snlzb",
        });
    });

    test("file", async () => {
        const response = await client.form1099Int.file("documentId_samplepWpJ9Snlzb");
        expect(response).toEqual({
            id: "documentId_samplepWpJ9Snlzb",
            userId: "userId_sampleXGMFnhOpeR",
            formFields: {},
            filingYear: 2023,
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "FILED",
            payer: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "Hooli",
                phoneNumber: "6501014096",
                tin: "*******11",
                tinFingerprint: "tinFingerprint_sample847jI1LwxF",
                tinVerificationId: "tinVerificationId_sample1b0E6efa89",
                tinVerificationStatus: "MATCH",
            },
            payee: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
                tin: "*******00",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            payerUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
            payeeUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
        });
    });

    test("correct", async () => {
        const response = await client.form1099Int.correct("documentId_samplepWpJ9Snlzb");
        expect(response).toEqual({
            id: "documentId_samplepWpJ9Snlzb",
            userId: "userId_sampleXGMFnhOpeR",
            formFields: {},
            filingYear: 2023,
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "FILED",
            payer: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "Hooli",
                phoneNumber: "6501014096",
                tin: "*******11",
                tinFingerprint: "tinFingerprint_sample847jI1LwxF",
                tinVerificationId: "tinVerificationId_sample1b0E6efa89",
                tinVerificationStatus: "MATCH",
            },
            payee: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
                tin: "*******00",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            payerUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
            payeeUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
        });
    });

    test("void", async () => {
        const response = await client.form1099Int.void("documentId_sample");
        expect(response).toEqual({
            id: "documentId_samplepWpJ9Snlzb",
            userId: "userId_sampleXGMFnhOpeR",
            formFields: {},
            filingYear: 2023,
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "FILED",
            payer: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "Hooli",
                phoneNumber: "6501014096",
                tin: "*******11",
                tinFingerprint: "tinFingerprint_sample847jI1LwxF",
                tinVerificationId: "tinVerificationId_sample1b0E6efa89",
                tinVerificationStatus: "MATCH",
            },
            payee: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
                tin: "*******00",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            payerUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
            payeeUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
        });
    });

    test("retrieve", async () => {
        const response = await client.form1099Int.retrieve("documentId_samplepWpJ9Snlzb");
        expect(response).toEqual({
            id: "documentId_samplepWpJ9Snlzb",
            userId: "userId_sampleXGMFnhOpeR",
            formFields: {},
            filingYear: 2023,
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "CREATED",
            payer: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "Hooli",
                phoneNumber: "6501014096",
                tin: "*******11",
                tinFingerprint: "tinFingerprint_sample847jI1LwxF",
                tinVerificationId: "tinVerificationId_sample1b0E6efa89",
                tinVerificationStatus: "MATCH",
            },
            payee: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
                tin: "*******00",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            payerUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
            payeeUrl: "https://documents.withabound.com/documentId_samplepWpJ9Snlzb",
        });
    });

    test("delete", async () => {
        const response = await client.form1099Int.delete("documentId_samplepWpJ9Snlzb");
        expect(response).toEqual({});
    });
});
