/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../src/api/index";
import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    sampleKey: process.env.appId_sampleqNhVcdYQYU.appSecret_sampleMz2Zbj3Hq || "test",
});

describe("FormW8BenE", () => {
    test("list", async () => {
        const response = await client.formW8BenE.list();
        expect(response).toEqual([
            {
                id: "documentId_sampleGyuBXlfAwo",
                createdAt: new Date("2024-01-01T00:00:00.000Z"),
                url: "https://documents.withabound.com/documents/documentId_sampleGyuBXlfAwo",
                payee: {
                    name: "Ada Lovelace",
                    incorporationCountry: "GB",
                    tin: "*******11",
                    permanentResidenceAddress: {
                        address: "43 Hilly Fields",
                        address2: "Suite 32",
                        city: "Lewisham",
                        state: "London",
                        postalCode: "SE13 7JN",
                        country: "GB",
                    },
                    mailingAddress: {
                        address: "256 Byron Street",
                        address2: "Suite 32",
                        city: "Palo Alto",
                        postalCode: "94306",
                        state: "CA",
                        country: "US",
                    },
                    tinType: "INDIVIDUAL",
                    tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                    tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                    tinVerificationStatus: "MATCH",
                },
                formFields: {
                    taxClassification: "CORPORATION",
                    isForeignTinNotRequired: false,
                    taxTreatyBenefits: {
                        residentCountry: "GB",
                        claimedProvision: "7",
                        rateOfWithholding: 0,
                        incomeCode: "17",
                        incomeType: "SERVICES",
                        additionalConditions: "Independent personal services performed in the US",
                    },
                    referenceNumbers: ["123456789"],
                    isCertified: true,
                    electronicSignature: {
                        signature: "Ada Lovelace",
                        printedName: "Ada Lovelace",
                        signedAt: new Date("2024-01-01T00:00:00.000Z"),
                        ipAddress: "127.0.0.1",
                    },
                },
            },
        ]);
    });

    test("create", async () => {
        const response = await client.formW8BenE.create({
            payee: {
                name: "Ada Lovelace",
                incorporationCountry: "GB",
                foreignTin: "111111111",
                permanentResidenceAddress: {
                    address: "43 Hilly Fields",
                    address2: "Suite 32",
                    city: "Lewisham",
                    state: "London",
                    postalCode: "SE13 7JN",
                    country: "GB",
                },
                mailingAddress: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    postalCode: "94306",
                    state: "CA",
                    country: "US",
                },
            },
            formFields: {
                taxClassification: Abound.W8BenETaxClassificationEnum.Corporation,
                isForeignTinNotRequired: false,
                taxTreatyCode: Abound.types.TaxTreatyAboundCodeEnum.Gb17IndependentPersonalServices,
                referenceNumbers: ["123456789"],
                isCertified: true,
                electronicSignature: {
                    signature: "Ada Lovelace",
                    printedName: "Ada Lovelace",
                    signedAt: new Date("2024-01-01T00:00:00.000Z"),
                    ipAddress: "127.0.0.1",
                },
            },
        });
        expect(response).toEqual({
            id: "documentId_sampleGyuBXlfAwo",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            url: "https://documents.withabound.com/documents/documentId_sampleGyuBXlfAwo",
            payee: {
                name: "Ada Lovelace",
                incorporationCountry: "GB",
                tin: "*******11",
                permanentResidenceAddress: {
                    address: "43 Hilly Fields",
                    address2: "Suite 32",
                    city: "Lewisham",
                    state: "London",
                    postalCode: "SE13 7JN",
                    country: "GB",
                },
                mailingAddress: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    postalCode: "94306",
                    state: "CA",
                    country: "US",
                },
                tinType: "INDIVIDUAL",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            formFields: {
                taxClassification: "CORPORATION",
                isForeignTinNotRequired: false,
                taxTreatyBenefits: {
                    residentCountry: "GB",
                    claimedProvision: "7",
                    rateOfWithholding: 0,
                    incomeCode: "17",
                    incomeType: "SERVICES",
                    additionalConditions: "Independent personal services performed in the US",
                },
                referenceNumbers: ["123456789"],
                isCertified: true,
                electronicSignature: {
                    signature: "Ada Lovelace",
                    printedName: "Ada Lovelace",
                    signedAt: new Date("2024-01-01T00:00:00.000Z"),
                    ipAddress: "127.0.0.1",
                },
            },
        });
    });

    test("retrieve", async () => {
        const response = await client.formW8BenE.retrieve("documentId_sampleVppNzzIbQT");
        expect(response).toEqual({
            id: "documentId_sampleGyuBXlfAwo",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            url: "https://documents.withabound.com/documents/documentId_sampleGyuBXlfAwo",
            payee: {
                name: "Ada Lovelace",
                incorporationCountry: "GB",
                tin: "*******11",
                permanentResidenceAddress: {
                    address: "43 Hilly Fields",
                    address2: "Suite 32",
                    city: "Lewisham",
                    state: "London",
                    postalCode: "SE13 7JN",
                    country: "GB",
                },
                mailingAddress: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    postalCode: "94306",
                    state: "CA",
                    country: "US",
                },
                tinType: "INDIVIDUAL",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinVerificationId: "tinVerificationId_sample41SD71AV8f",
                tinVerificationStatus: "MATCH",
            },
            formFields: {
                taxClassification: "CORPORATION",
                isForeignTinNotRequired: false,
                taxTreatyBenefits: {
                    residentCountry: "GB",
                    claimedProvision: "7",
                    rateOfWithholding: 0,
                    incomeCode: "17",
                    incomeType: "SERVICES",
                    additionalConditions: "Independent personal services performed in the US",
                },
                referenceNumbers: ["123456789"],
                isCertified: true,
                electronicSignature: {
                    signature: "Ada Lovelace",
                    printedName: "Ada Lovelace",
                    signedAt: new Date("2024-01-01T00:00:00.000Z"),
                    ipAddress: "127.0.0.1",
                },
            },
        });
    });
});
