/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    token: process.env.TESTS_AUTH || "test",
});

describe("Mailings", () => {
    test("list", async () => {
        const response = await client.mailings.list();
        expect(response).toEqual([
            {
                to: {
                    address: "256 Byron Street",
                    address2: "Suite 32",
                    city: "Palo Alto",
                    state: "CA",
                    postalCode: "94306",
                    country: "US",
                    name: "Ada Lovelace",
                    name2: "InGen Corporation",
                },
                from: {
                    address: "1401 N Shoreline Blvd",
                    address2: "Suite 1",
                    city: "Mountain View",
                    state: "CA",
                    postalCode: "94043",
                    country: "US",
                    name: "Hooli",
                    name2: "InGen Corporation",
                },
                id: "mailingId_sampleFV9b73IvAD",
                createdAt: new Date("2024-01-01T00:00:00.000Z"),
                status: "CREATED",
                url: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/documents/FORM-1099-COPY-B.pdf",
                userId: "{{userId}}",
                mailedFromId: "documentId_sampletTtqNfulW8",
            },
        ]);
    });

    test("retrieve", async () => {
        const response = await client.mailings.retrieve("{{mailingId}}");
        expect(response).toEqual({
            to: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
            },
            from: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "InGen Corporation",
            },
            id: "mailingId_sampleFV9b73IvAD",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "CREATED",
            url: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/documents/FORM-1099-COPY-B.pdf",
            userId: "{{userId}}",
            mailedFromId: "documentId_sampletTtqNfulW8",
        });
    });

    test("update", async () => {
        const response = await client.mailings.update("{{mailingId}}", {
            "Idempotency-Key": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
            body: {
                to: {},
                from: {},
            },
        });
        expect(response).toEqual({
            to: {
                address: "256 Byron Street",
                address2: "Suite 32",
                city: "Palo Alto",
                state: "CA",
                postalCode: "94306",
                country: "US",
                name: "Ada Lovelace",
                name2: "InGen Corporation",
            },
            from: {
                address: "1401 N Shoreline Blvd",
                address2: "Suite 1",
                city: "Mountain View",
                state: "CA",
                postalCode: "94043",
                country: "US",
                name: "Hooli",
                name2: "InGen Corporation",
            },
            id: "mailingId_sampleFV9b73IvAD",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            status: "CREATED",
            url: "https://tax-documents-sandbox.s3.us-west-2.amazonaws.com/documents/FORM-1099-COPY-B.pdf",
            userId: "{{userId}}",
            mailedFromId: "documentId_sampletTtqNfulW8",
        });
    });

    test("delete", async () => {
        const response = await client.mailings.delete("{{mailingId}}");
        expect(response).toEqual({ key: "value" });
    });
});
