/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    sampleKey: process.env.appId_sampleqNhVcdYQYU.appSecret_sampleMz2Zbj3Hq || "test",
});

describe("TaxTreaties", () => {
    test("list", async () => {
        const response = await client.taxTreaties.list();
        expect(response).toEqual([
            {
                taxTreatyCode: "CN_42_PUBLIC_ENTERTAINMENT",
                residentCountry: "CN",
                rateOfWithholding: 0,
                incomeDescription: "Public entertainment performed in the US",
            },
            {
                taxTreatyCode: "GB_17_INDEPENDENT_PERSONAL_SERVICES",
                residentCountry: "GB",
                rateOfWithholding: 0,
                incomeDescription: "Independent personal services",
            },
        ]);
    });
});
