/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    apiKey: process.env.TESTS_AUTH || "test",
});

describe("TinVerifications", () => {
    test("list", async () => {
        const response = await client.tinVerifications.list();
        expect(response).toEqual([
            {
                name: "Ada Lovelace",
                id: "tinVerificationId_sample41SD71AV8f",
                createdAt: "2024-01-01T00:00:00.000Z",
                status: "MATCH",
                tin: "*******00",
                tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
                tinType: "INDIVIDUAL",
            },
        ]);
    });

    test("create", async () => {
        const response = await client.tinVerifications.create({
            body: {
                name: "Ada Lovelace",
                tin: "000000000",
            },
        });
        expect(response).toEqual({
            name: "Ada Lovelace",
            id: "tinVerificationId_sample41SD71AV8f",
            createdAt: "2024-01-01T00:00:00.000Z",
            status: "MATCH",
            tin: "*******00",
            tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
            tinType: "INDIVIDUAL",
        });
    });

    test("retrieve", async () => {
        const response = await client.tinVerifications.retrieve("tinVerificationId_sample41SD71AV8f");
        expect(response).toEqual({
            name: "Ada Lovelace",
            id: "tinVerificationId_sample41SD71AV8f",
            createdAt: "2024-01-01T00:00:00.000Z",
            status: "MATCH",
            tin: "*******00",
            tinFingerprint: "tinFingerprint_samplehy2BWO6JJG",
            tinType: "INDIVIDUAL",
        });
    });
});
