/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    sampleKey: process.env.appId_sampleqNhVcdYQYU.appSecret_sampleMz2Zbj3Hq || "test",
});

describe("Users", () => {
    test("list", async () => {
        const response = await client.users.list();
        expect(response).toEqual([
            {
                id: "userId_sampleXGMFnhOpeR",
                createdAt: new Date("2024-01-01T00:00:00.000Z"),
                email: "your-users-email@example.com",
                foreignId: "my-foreign-id",
                metadata: { "my-key": "my-value" },
            },
        ]);
    });

    test("create", async () => {
        const response = await client.users.create({
            body: {
                email: "your-users-email@example.com",
                foreignId: "my-foreign-id",
                metadata: {
                    "my-key": "my-value",
                },
            },
        });
        expect(response).toEqual({
            id: "userId_sampleXGMFnhOpeR",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            email: "your-users-email@example.com",
            foreignId: "my-foreign-id",
            metadata: { "my-key": "my-value" },
        });
    });

    test("retrieve", async () => {
        const response = await client.users.retrieve("userId_sampleXGMFnhOpeR");
        expect(response).toEqual({
            id: "userId_sampleXGMFnhOpeR",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            email: "your-users-email@example.com",
            foreignId: "my-foreign-id",
            metadata: { "my-key": "my-value" },
        });
    });

    test("update", async () => {
        const response = await client.users.update("userId_sampleXGMFnhOpeR", {
            email: "your-users-email@example.com",
            foreignId: "my-foreign-id",
            metadata: {
                "my-key": "my-value",
            },
        });
        expect(response).toEqual({
            id: "userId_sampleXGMFnhOpeR",
            createdAt: new Date("2024-01-01T00:00:00.000Z"),
            email: "your-users-email@example.com",
            foreignId: "my-foreign-id",
            metadata: { "my-key": "my-value" },
        });
    });
});
