/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AboundClient } from "../../src/Client";

const client = new AboundClient({
    environment: process.env.TESTS_BASE_URL || "test",
    sampleKey: process.env.TESTS_AUTH || "test",
});

describe("Users", () => {
    test("list", async () => {
        const response = await client.users.list();
        expect(response).toEqual([
            { id: "userId_sampleXGMFnhOpeR", createdAt: "2024-01-01T00:00:00.000Z", foreignId: "my-foreign-id" },
        ]);
    });

    test("create", async () => {
        const response = await client.users.create({
            body: {
                foreignId: "my-foreign-id",
            },
        });
        expect(response).toEqual({
            id: "userId_sampleXGMFnhOpeR",
            createdAt: "2024-01-01T00:00:00.000Z",
            foreignId: "my-foreign-id",
        });
    });

    test("retrieve", async () => {
        const response = await client.users.retrieve("userId_sampleXGMFnhOpeR");
        expect(response).toEqual({
            id: "userId_sampleXGMFnhOpeR",
            createdAt: "2024-01-01T00:00:00.000Z",
            foreignId: "my-foreign-id",
        });
    });

    test("update", async () => {
        const response = await client.users.update("userId_sampleXGMFnhOpeR", {
            foreignId: "my-foreign-id",
        });
        expect(response).toEqual({
            id: "userId_sampleXGMFnhOpeR",
            createdAt: "2024-01-01T00:00:00.000Z",
            foreignId: "my-foreign-id",
        });
    });
});
