/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../index";

/**
 * @example
 *     {
 *         body: {
 *             email: "your-users-email@example.com",
 *             foreignId: "my-foreign-id",
 *             metadata: {
 *                 "my-key": "my-value"
 *             }
 *         }
 *     }
 */
export interface UsersCreateRequest {
    "Idempotency-Key"?: Abound.types.IdempotencyKey | undefined;
    body: Abound.UserRequestSchema;
}
