/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../errors/index";
import * as Abound from "../../../../../index";

export class ConflictErrorSchema extends errors.AboundError {
    constructor(body: Abound.types.DefaultErrorSchema) {
        super({
            message: "ConflictErrorSchema",
            statusCode: 409,
            body: body,
        });
        Object.setPrototypeOf(this, ConflictErrorSchema.prototype);
    }
}
