name: "CodeQL Scheduled Action"

on:
  schedule:
    - cron: "0 5 * * 1-5" # At 05:00 on every day-of-week from Monday through Friday.

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#deployments"
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#deployments"
        if: always()
