on:
  release:
    types:
      - published

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate release version and package version match
        env:
          RELEASE_TAG_NAME: ${{github.event.release.tag_name}}
        run: |
          if ! grep -q "\"version\": \"${RELEASE_TAG_NAME:1}\"" package.json
            then
              echo "Release tag (${RELEASE_TAG_NAME:1}) does not match the package.json version"
              exit 1
            else
              echo "Release tag matches the package.json version"
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: npm ci
      - run: npm run build

      - name: Publish @withabound/node-sdk
        id: npm-publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{secrets.NPM_ACCESS_TOKEN}}
          access: public

      - name: Send Slack notification
        if: ${{steps.npm-publish.outputs.type}}
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          text: "@withabound/node-sdk@${{steps.npm-publish.outputs.version}} has been published."
        env:
          INCOMING_WEBHOOK_URL: ${{secrets.SUCCESS_DEPLOYMENT_PRODUCT_URL}}

      - run: ./smoke_test_npm_release.sh
        env:
          ABOUND_SMOKE_TEST_APP_ID: ${{secrets.ABOUND_SMOKE_TEST_APP_ID}}
          ABOUND_SMOKE_TEST_APP_SECRET: ${{secrets.ABOUND_SMOKE_TEST_APP_SECRET}}
