on:
  release:
    types:
      - published

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#deployments"
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate release version and package version match
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          if ! grep -q "\"version\": \"${RELEASE_TAG_NAME:1}\"" package.json
            then
              echo "Release tag (${RELEASE_TAG_NAME:1}) does not match the package.json version"
              exit 1
            else
              echo "Release tag matches the package.json version"
          fi

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install npm dependencies
        run: npm ci

      - name: Publish @withabound/node-sdk
        id: npm-publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#deployments"
        if: always()

      - name: Slack notification
        if: steps.npm-publish.outputs.type != 'none'
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          text: "@withabound/node-sdk@${{ steps.npm-publish.outputs.version }} has been published."
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SUCCESS_DEPLOYMENT_DX_URL }}
