/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The account number or other unique number assigned to distinguish an account. Abound will auto-generate this for you if left omitted.
 */
export type Form1099AccountNumber = string;
