/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../../index";

export interface Form1099BaseCorrectRequestSchema {
    userId?: Abound.types.UserId;
    payee: Abound.types.PayeeRequestSchema;
}
