/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Form1099StatusEnum = "CREATED" | "FILED" | "ACCEPTED" | "REJECTED";

export const Form1099StatusEnum = {
    Created: "CREATED",
    Filed: "FILED",
    Accepted: "ACCEPTED",
    Rejected: "REJECTED",
} as const;
