/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Abound from "../../../../../index";

export interface Form1099StateTaxInfoSchema {
    filingState: Abound.types.Form1099FilingStateEnum;
    /** The payee's state identification number. */
    payeeStateId?: string;
    /** The payer's state identification number. */
    payerStateId?: string;
    /** The state tax withheld. Value must be in cents. Abound does not currently support `stateTaxWithheld` reporting, please contact us for more information. */
    stateTaxWithheld?: number;
}
